--Q1. What is the total revenue generated by male vs. female customers?

SELECT gender, SUM(purchase_amount) as revenue
FROM customer
GROUP BY gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id , purchase_amount from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);

--Q3. Which are the top 5 products with the highest average review rating?
SELECT
    item_purchased,
    ROUND(AVG(review_rating)::numeric, 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY "Average Product Rating" DESC
LIMIT 5;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type , ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status ,
count(customer_id) as total_customers ,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;



--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased , 
ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT
    CASE
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer
GROUP BY customer_segment
ORDER BY customer_count DESC;

--Q8. What are the top 3 most purchased products within each category?
SELECT
    category,
    item_purchased,
    purchase_count
FROM (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM customer
    GROUP BY category, item_purchased
) ranked_products
WHERE rn <= 3
ORDER BY category, purchase_count DESC;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT
    subscription_status,
    COUNT(*) AS customer_count,
    ROUND(
        (COUNT(*)::NUMERIC /
        SUM(COUNT(*)) OVER ()) * 100,
        2
    ) AS percentage
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;
--Q10. What is the revenue contribution of each age group?
SELECT
    CASE
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 45 THEN '36-45'
        WHEN age BETWEEN 46 AND 55 THEN '46-55'
        ELSE '56+'
    END AS age_group,
    ROUND(SUM(purchase_amount)::NUMERIC, 2) AS revenue,
    ROUND(
        (SUM(purchase_amount)::NUMERIC /
        SUM(SUM(purchase_amount)) OVER ()) * 100,
        2
    ) AS revenue_contribution_percentage
FROM customer
GROUP BY age
ORDER BY revenue DESC;